apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "redis-master"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        name: "redis-master"
    spec:
      containers:
        - name: redis
          image: launcher.gcr.io/google/redis4
          args:
            - /etc/redis/redis.conf
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
          volumeMounts:
            - name: "redisconfig"
              mountPath: "/etc/redis"
            - name: "redis-data"
              mountPath: "/var/lib/redis"
      volumes:
        - name: "redis-data"
          persistentVolumeClaim:
            claimName: redisdata-master
        - name: "redisconfig"
          configMap:
            name: "redis-master"
            items:
              - key: "redis.conf"
                path: "redis.conf"