kind: Service
apiVersion: v1
metadata:
  name: "redis-slave"
spec:
  selector:
    app: "redis"
    name: "redis-slave"
  ports:
    - name: "redis"
      protocol: "TCP"
      port: 6379
      targetPort: 6379