apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfig
data:
  nginx.conf: |
    worker_processes 5;
	
	upstream backend {
        server 127.0.0.1:8000
    }
    
    server {
    listen 8001;
    
    gzip            on;
    gzip_proxied    any;
    gzip_com_level  5;
    gzip_types      application/json text/plain;
    
        location / {
            lua_need_request_body off;
            access_by_lua_file /etc/nginx/conrad-auth.lua;
            proxy_pass http://backend;
            try_files $uri $uri/ =404;
        }
    }